[package]
org = "ballerina"
name = "cache"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["cache", "LRU"]
repository = "https://github.com/ballerina-platform/module-ballerina-cache"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/cache-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/cache-test-utils-@project.version@.jar"
scope = "testOnly"
