[package]
org = "ballerina"
name = "cache"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["cache", "LRU"]
repository = "https://github.com/ballerina-platform/module-ballerina-cache"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/cache-native-@project.version@.jar"
