[package]
org = "ballerina"
name = "cache"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["cache", "LRU"]
repository = "https://github.com/ballerina-platform/module-ballerina-cache"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "cache-native"
version = "@toml.version@"
path = "../native/build/libs/cache-native-@project.version@.jar"
