[package]
org = "ballerina"
name = "cache"
version = "3.2.0"
authors = ["Ballerina"]
keywords = ["cache", "LRU"]
repository = "https://github.com/ballerina-platform/module-ballerina-cache"
icon = "resources/icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/cache-native-3.2.0-SNAPSHOT.jar"
