[package]
org = "ballerina"
name = "cache"
version = "3.9.0"
authors = ["Ballerina"]
keywords = ["cache", "LRU"]
repository = "https://github.com/ballerina-platform/module-ballerina-cache"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "cache-native"
version = "3.9.0"
path = "../native/build/libs/cache-native-3.9.0.jar"
