[project]
org-name = "ballerina"
version = "2.0.0"

[dependencies]
"ballerina/task" = "1.1.0"
"ballerina/log" = "1.0.0"
"ballerina/time" = "1.0.1"
"ballerina/runtime" = "0.5.0"
"ballerina/io" = "0.5.0"
"ballerina/system" = "0.6.0"
"ballerina/stringutils" = "0.5.0"
"ballerina/config" = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "cache"
    version = "2.0.0-SNAPSHOT"
    path = "../cache-native/build/libs/cache-native-2.0.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["cache"]
