[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/task" = "@stdlib.task.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/config" = "@stdlib.config.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "cache"
    version = "@project.version@"
    path = "../cache-native/build/libs/cache-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["cache"]
